# Generated by Django 5.2.2 on 2025-06-09 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='watchedurl',
            name='last_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='watchedurl',
            unique_together={('user', 'url')},
        ),
    ]
